article/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'article'  # 一定要写这一行，否则html中会报错 'article' is not a registered namespace

urlpatterns = [
    path(r'article_post/', views.article_post, name='article_post'),
    path(r'article_list/', views.article_list, name='article_list'),
    path(r'article_detail/<int:id>/', views.article_detail, name='article_detail'),
    path(r'like_article/', views.like_article, name='like_article'),
]

django_auth_example/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls')),
    path(r'users/', include('django.contrib.auth.urls')),
    path(r'$/', views.index, name='base'),
    path(r'article/', include('article.urls')),

]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'register/', views.register, name='register'),
    url(r'user_info/', views.user_info, name='user_info'),
    url(r'user_info_edit/', views.myself_edit, name='user_info_edit'),
    url(r'upload_image/', views.my_image, name='upload_image')
]

templates/article_list.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}
{% block title %}
    首页
{% endblock %}

{% block body %}
    <style>
        body {
            background: #E6E6E6;
        }
    </style>
{% endblock %}
{#在{% block main %}的这个标签外面加一层<div class="main"></div>然后修改.main的css样式即可#}
<div class="main">

    {% block main %}
        <ul class="question-list-group">
            {% for article in articles %}
                <li>
                    <div class="question-group">
                        <p class="question-title">
                            <a href="{% url 'article:article_detail' article.id %}">{{ article.title }}</a>
                        </p>
                        <p class="question-content">{{ article.content }}</p>
                        <div class="question-info">
                            <span class="question-author">{{ article.author.username }} </span>
                            <span class="question-time">{{ article.create_time }}</span>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>

        <style>
            ul {
                list-style: none;
                padding-left: 0;
            }

            ul li {
                border-bottom: 1px solid #eee;
                overflow: hidden;
                /*padding: 15px 0;*/
            }

            .main {
                background: #fff;
                width: 750px;
                margin: 0 auto;
                overflow: hidden;
                padding: 10px;
            }

            .question-group {
                float: left;
                width: 660px;
                margin-left: 10px;
            }

            .question-title a {
                color: #259;
                font-weight: 900;
            }

            .question-info {
                text-align: right;
            }

            .question-author {
                margin-right: 20px;
            }
        </style>
    {% endblock %}
</div>

templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    {% block head %}{% endblock %}

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="navbar-static-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'base' %}">ACV博客系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {#                class=active表示将此栏默认选中#}
                <li class="active"><a href="#">首页</a></li>
                <li><a href="#about">问答</a></li>
                <li><a href="#contact">文件</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false"> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'article:article_post' %}">发表博客</a></li>
                        <li><a href="#">发布问答</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    {% if user.is_authenticated %}
                        <a href="/users/user_info/">{{ user.username }}</a>
                    {% else %}
                        <a href="/users/login/">登录</a>
                    {% endif %}
                </li>
                <li>
                    {% if user.is_authenticated %}
                        <a href=" {% url 'logout' %} ">注销</a>
                    {% else %}
                        <a href="{% url 'users:register' %}">注册</a>
                    {% endif %}
                </li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="main">
    {% block main %} {% endblock %}
</div>
{% block body %}
{% endblock %}
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
<style>


    body {
        background: #E6E6E6;

    }

</style>
</html>

templates/imagecrop.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/imagecrop.css' %}">
<div class="container">
    <div class="imageBox">
        <div class="thumbBox"></div>
        <div class="spinner" style="display: none"></div>
    </div>

    <div class="action">
        <!-- <input type="file" id="file" style=" width: 200px">-->
        <div class="new-contentarea tc">
            <a href="javascript:void(0)" class="upload-img">
                <label for="upload-file">请先选择图片...</label>
            </a>
            <input type="file" class="" name="upload-file" id="upload-file"/>
        </div>
        <input type="button" id="btnCrop" class="Btnsty_peyton" value="OK"><!--注意这行代码，添加了 id="btnCrop" -->
        <input type="button" id="btnZoomIn" class="Btnsty_peyton" value="+">
        <input type="button" id="btnZoomOut" class="Btnsty_peyton" value="-">
    </div>
    <div class="cropped"></div>
</div>

<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/cropbox-min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
<script type="text/javascript">
    $(window).load(function () {
        var options =
            {
                thumbBox: '.thumbBox',
                spinner: '.spinner',
                imgSrc: ''
            }
        var cropper = $('.imageBox').cropbox(options);
        var img = "";
        $('#upload-file').on('change', function () {
            var reader = new FileReader();
            reader.onload = function (e) {
                options.imgSrc = e.target.result;
                cropper = $('.imageBox').cropbox(options);
                getImg();
            }
            reader.readAsDataURL(this.files[0]);
            this.files = [];
        })
        $('#btnCrop').on('click', function () {
            //alert("图片上传喽");
            $.ajax({
                url: '{% url "users:upload_image" %}',
                type: 'POST',
                data: {"img": img},
                success: function (e) {
                    //location.href= "{% url 'users:user_info' %}"
                    if (e == "1") {
                        parent.location.reload();
                    } else {
                        alert("图片上传失败，请重试！.")
                    }
                },
            })
        })

        function getImg() {
            img = cropper.getDataURL();
            $('.cropped').html('');
            $('.cropped').append('<img src="' + img + '" align="absmiddle" style="width:180px; margin-top:4px; border-radius:180px; box-shadow:0px 0px 12px #7E7E7E;"> <p>180px*180px</p>');
            $('.cropped').append('<img src="' + img + '" align="absmiddle" style="width:128px; margin-top:4px; border-radius:128px; box-shadow:0px 0px 12px #7E7E7E;"> <p>128px*128px</p>');
            $('.cropped').append('<img src="' + img + '" align="absmiddle" style="width:64px; margin-top:4px; border-radius:64px; box-shadow:0px 0px 12px #7E7E7E;" > <p>64px*64px</p>');
        }

        $(".imageBox").on("mouseup", function () {
            getImg();
        });
        $('#btnZoomIn').on('click', function () {
            cropper.zoomIn();
        })
        $('#btnZoomOut').on('click', function () {
            cropper.zoomOut();
        })
    });
</script>

templates/index.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>首页</title>
    <link rel="stylesheet" href="https://unpkg.com/mobi.css/dist/mobi.min.css">
</head>
<body>
<div class="flex-center">
    <div class="container">
        <div>
            <h1 class="logo"><a href="{% url 'index' %}">Django Auth Example</a></h1>
            {#            当用户已经登录时返回 True，否则返回 False#}
            {% if user.is_authenticated %}
                <p>你已登录，欢迎你：<a href="#">{{ user.username }}</a></p>
                <button class="btn btn-default">
                    <a href="{% url 'logout' %}?next={{ request.path }}">注销登录</a>
                </button>
                <button class="btn btn-default">
                    <a href="{% url 'password_change' %}?next={{ request.path }}">修改密码</a>
                </button>
            {% else %}
                <p>你还没有登录，请
                    <button class="btn btn-default"><a href="{% url 'login' %}?next={{ request.path }}">登录</a></button>
                    或者
                    <button class="btn btn-default"><a href="{% url 'users:register' %}">注册</a></button>
                </p>
            {% endif %}
        </div>
    </div>
</div>
</body>
</html>

templates/user_info_edit.html
{% extends "base.html" %}
{% block head %}
    <script src="http://how2j.cn/study/js/jquery/2.0.0/jquery.min.js"></script>
    <link href="http://how2j.cn/study/css/bootstrap/3.3.6/bootstrap.min.css" rel="stylesheet">
    <script src="http://how2j.cn/study/js/bootstrap/3.3.6/bootstrap.min.js"></script>
    <style>
        div {
            margin: 5px;
        }
    </style>
{% endblock %}
{% block title %}用户信息修改{% endblock %}
{% block body %}
    <div class="row text-center vertical-middle-sm">
        <h1>编辑我的信息</h1>
        <div class="row">
            <div class="col-md-6">
                <form class="form-horizontal" action="." method="post">{% csrf_token %}
                    <div class="row">
                        <div class="col-md-4 text-right"><span>用户名:</span></div>
                        <div class="input-group">
                            <input type="text" name="username" disabled="disabled" value="{{ user.username }}"
                                   class="form-control"
                                   aria-describedby="basic-addon1">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 text-right"><span>邮箱:</span></div>
                        <div class="input-group">
                            <input type="text" disabled="disabled" value="{{ user.email }}" class="form-control"
                                   aria-describedby="basic-addon1">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 text-right"><span>毕业学校:</span></div>
                        <div class="input-group">
                            <input type="text" name="school" value="{{ user.school }}" class="form-control"
                                   aria-describedby="basic-addon1">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 text-right"><span>职业:</span></div>
                        <div class="input-group">
                            <input type="text" name="profession" value="{{ user.profession }}" class="form-control"
                                   aria-describedby="basic-addon1">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 text-right"><span>地址:</span></div>
                        <div class="input-group">
                            <input type="text" name="address" value="{{ user.address }}" class="form-control"
                                   aria-describedby="basic-addon1">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4 text-right"><span>个人介绍:</span></div>
                        <div class="input-group">
                            <input type="text" name="aboutme" value="{{ user.aboutme }}" class="form-control"
                                   aria-describedby="basic-addon1">
                        </div>
                    </div>
                    <div class="row">
                        <input type="submit" class="btn btn-primary btn-lg" value="提交">
                    </div>
                </form>
            </div>
        </div>

    </div>
{#    <style>#}
{#    .row{#}
{#        text-align:center;#}
{#    }#}
{#    </style>#}
{% endblock %}

templates/users_info.html
{% extends "base.html" %}
{% block title %}用户信息{% endblock %}
{% block body %}

    <div class="row text-center vertical-middle-sm">
        <h1>我的信息</h1>
        <div class="row">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-4 text-right"><span>用户名:</span></div>
                    <div class="col-md-8 text-left">{{ user.username }}</div>
                </div>
                <div class="row">
                    <div class="col-md-4 text-right"><span>邮箱:</span></div>
                    <div class="col-md-8 text-left">{{ user.email }}</div>
                </div>
                <div class="row">
                    <div class="col-md-4 text-right"><span>毕业学校:</span></div>
                    <div class="col-md-8 text-left">{{ user.school }}</div>
                </div>
                <div class="row">
                    <div class="col-md-4 text-right"><span>职业:</span></div>
                    <div class="col-md-8 text-left">{{ user.profession }}</div>
                </div>
                <div class="row">
                    <div class="col-md-4 text-right"><span>地址:</span></div>
                    <div class="col-md-8 text-left">{{ user.address }}</div>
                </div>
                <div class="row">
                    <div class="col-md-4 text-right"><span>个人介绍:</span></div>
                    <div class="col-md-8 text-left">{{ user.aboutme }}</div>
                </div>
                <div class="row" style="float:left ;margin-left:150px">
                    <a href="{% url 'users:user_info_edit' %}">
                        <button class="btn btn-primary btn-lg">编辑我的信息</button>
                    </a>
                </div>
            </div>
            {% load staticfiles %}
            <div style="margin-right:100px">

                {% if user.photo %}
                    <img src="{{ user.photo | striptags }}" class="img-circle" id="my_photo" width="120px"
                         name="user_face">
                {% else %}
                    <img name="user_face" src="{% static 'images/user.jpg' %}" class="img-circle" id="my_photo"
                         width="140px">
                {% endif %}
                <div style="margin-right:3px">
                    {#                    <a href="{% url 'users:upload_image' %}">#}
                    <button class="btn btn-primary btn-lg" id="upload_image" onclick="upload_image_layer()">
                        上传头像
                    </button>
                    {#                    </a>#}
                </div>
            </div>
        </div>

        <script type="text/javascript" src='{% static "js/jquery-1.11.1.min.js" %}'></script>
        <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
        <script>
            function upload_image_layer() {
                layer.open({
                    title: "上传头像",
                    area: ['600px', '550px'],
                    type: 2,
                    content: "{% url 'users:upload_image' %}",
                });
            }
        </script>
{% endblock %}