article/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'article'  # 一定要写这一行，否则html中会报错 'article' is not a registered namespace

urlpatterns = [
    path(r'article_post/', views.article_post, name='article_post'),
    path(r'article_list/', views.article_list, name='article_list'),
    path(r'article_detail/<int:id>/', views.article_detail, name='article_detail'),
    path(r'like_article/', views.like_article, name='like_article'),
]

django_auth_example/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'users/', include('users.urls')),
    path(r'users/', include('django.contrib.auth.urls')),
    path(r'$/', views.index, name='base'),
    path(r'article/', include('article.urls')),

]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'register/', views.register, name='register'),
    url(r'user_info/', views.user_info, name='user_info'),
    url(r'user_info_edit/', views.myself_edit, name='user_info_edit'),
    url(r'upload_image/', views.my_image, name='upload_image')
]

article/models.py
from django.db import models

# Create your models here.

from django.db import models
from users.models import User
from django.utils import timezone
from django.urls import reverse


class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="article", null=True)
    title = models.CharField(max_length=200)
    content = models.TextField(null=True)
    created = models.DateTimeField(default=timezone.now, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    users_like = models.ManyToManyField(User, related_name="articles_like", blank=True)

    class Meta:
        ordering = ("-updated",)

    # 对数据库中的这两个字段建立索引，以后就可以通过每篇文章的id和slug来获取该文章对象了，
    # 这样建立索引以后，能提高读取文章对象的速度。
    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name="comments")
    commentator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commentator", null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return "Comment by {0} on {1}".format(self.commentator.username, self.article)

article/forms.py
from django import forms
from .models import Article, Comment


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ("title", "content")


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("commentator", "body",)

article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ArticlePostForm, CommentForm
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from .models import Article, Comment
from django.views.decorators.http import require_POST
from django.utils import timezone
from users.models import User


# Create your views here.
def article_out(request):
    return render(request, 'article/article.html')


def article_list(request):
    articles = Article.objects.all()
    return render(request, 'article_list.html', {'articles': articles})


@login_required(login_url='/users/login')
@csrf_exempt
def article_post(request):
    user = User.objects.get(username=request.user.username)
    if request.method == "POST":
        article_post_form = ArticlePostForm(request.POST)
        if article_post_form.is_valid():
            # cd = article_post_form.cleaned_data
            try:
                new_article = Article()
                # new_article=Article.objects.create_article(title,content)
                # new_article = article_post_form.save(commit=False)
                author = user
                new_article.author = author
                title = request.POST.get('title', None)
                content = request.POST.get('content', None)
                new_article.title = title
                new_article.content = content
                new_article.save()
                return redirect('article:article_list')
            except:
                return HttpResponse("2")
    else:
        article_post_form = ArticlePostForm()

        return render(request, "article/article.html",
                      {"article_post_form": article_post_form})

@login_required(login_url='/users/login/')
def article_detail(request, id):
    article = Article.objects.get(id=id)
    user = User.objects.get(username=request.user.username)
    if request.method == "POST":
        comment = request.POST.get('comment', None)
        # article_id = request.POST.get('article_id', None)
        new_comment = Comment()
        new_comment.article = article
        new_comment.body = comment
        new_comment.commentator = user
        new_comment.save()
    else:
        pass
    return render(request, 'article/article_detail.html', {'article': article, })


@csrf_exempt
@require_POST
@login_required(login_url='/users/login/')
def like_article(request):
    article_id = request.POST.get("id")
    action = request.POST.get("action")
    if article_id and action:
        try:
            article = Article.objects.get(id=article_id)
            if action == "like":
                article.users_like.add(request.user)
                return HttpResponse("1")
            else:
                article.users_like.remove(request.user)
                return HttpResponse("2")
        except:
            return HttpResponse("no")

templates/article/article.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}发表博客{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% endblock %}

<div class="main">
    {% block main %}
        <h3 class="page-title">发表博客</h3>
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-container">
                <div class="form-group">
                    <input id="id_title" class="form-control" type="text" placeholder="请输入标题" name="title">
                </div>
                <div id="editormd" class="col-md-10 text-left">
                    <textarea name="content" style="display:none;"></textarea>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary" onclick="publish_article()">立即发布</button>
                </div>
            </div>
        </form>
        <style>
            .form-container {
                width: 800px;
                margin: 0 auto;
                text-align: right;
            }

            .page-title {
                text-align: center;
            }

            body {
                background: #E6E6E6;
            }

            .main {
                background: #fff;
                width: 1000px;
                margin: 0 auto;
                overflow: hidden;
                padding: 10px;
            }
        </style>

        <script type="text/javascript" src='{% static "js/jquery-1.11.1.min.js" %}'></script>
        <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
        <script type="text/javascript">
            function publish_article() {
                {#var title = $("#id_title").val();#}
                {#var body = $("#id_body").val();#}
                {#var article_tags = [];#}
                {#$.each($("input[name='article_tag']:checked"), function () {#}
                {#    article_tags.push($(this).val());});#}
                {#"tags": JSON.stringify(article_tags)#}
                $.ajax({
                    url: "{% url 'article:article_post' %}",
                    dataType:"text",
                    type: "GET"
                    {#data: {"title": title, },#}
                    success: function (e) {
                        if (e == "1") {
                            layer.msg("发布成功！", {
                                time: 700,
                                end: function () {
                                    location.href = "{% url 'article:article_list' %}";//修改后：文章发布成功后跳转到文章列表
                                }
                            });
                        } else if (e == "2") {
                            layer.msg("发布失败，请重试！", {
                                time: 700,
                                end: function () {
                                }
                            });
                        }
                    },
                });
            }
        </script>
        <script type="text/javascript" src='{% static "editor/editormd.min.js" %}'></script>
        <script type="text/javascript">
            $(function () {
                var editor = editormd("editormd", {
                    width: "100%",
                    height: 640,
                    syncScrolling: "single",
                    path: "{% static 'editor/lib/' %}"
                });
            });
        </script>
    {% endblock %}
</div>

templates/article/article_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}文章详情{% endblock %}

{% block head %}

{% endblock %}

<div class="main">
    {% block main %}
        {% with total_likes=article.users_like.count users_like=article.users_like.all %}
            <h3 class="page-title">{{ article.title }}</h3>
            <p class="question-info">
                <span class="span">博主：{{ article.author.username }}</span>
                <span>发表时间:{{ article.created }}</span>
                <span style="margin-left:20px"
                      class="glyphicon glyphicon-thumbs-up">{{ total_likes }}like{{ total_likes|pluralize }}</span>
            </p>


            <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}"/>
            <div id='editormd-view'>
        <textarea id="append-test" style="display:none;" class="question-content">
{{ article.content }}
        </textarea>
            </div>
            <div>
                <p class="text-center">
                    <a onclick="like_article({{ article.id }}, 'like')" href="#">
                        <span class="glyphicon glyphicon-thumbs-up">like</span>
                    </a>
                    <a onclick="like_article({{ article.id }}, 'unlike')" href="#">
                        <span style="margin-left: 15px;" class="glyphicon glyphicon-thumbs-down">unlike</span>
                    </a>
                </p>
            </div>
            <div>
                <p class="text-center"><strong>点赞本文的读者</strong></p>
                {% for user in article.users_like.all %}
                    <p class="text-center">{{ user.username }}</p>
                {% empty %}
                    <p class="text-center">还没有人对此文章表态</p>
                {% endfor %}
            </div>
            <h3><span class="glyphicon glyphicon-bullhorn"></span>本文有
                {{ article.comments.count }}
                条评论</h3>
            <div>
                <ul class="answer-list">
                    {% for comment in article.comments.all %}
                        <div class="user-info">
                            {#                    <img src="{{ url_for('static',filename='') }}"alt="" class="avatar">#}
                            <span class="username">{{ comment.commentator }}</span>
                            <span class="create-time">{{ comment.created }}</span>
                        </div>
                        <p class="answer-content">{{ comment.body }}</p>
                        <hr>
                    {% endfor %}
                </ul>

{#                {% for comment in article.comments.all %}#}
{#                    <div>#}
{#                        <p><strong>{{ comment.commentator }}</strong>说:</p>#}
{#                        <p style="margin-left:40px;">{{ comment.body }}</p>#}
{#                    </div>#}
{#                {% empty %}#}
{#                    <p>没有评论</p>#}
{#                {% endfor %}#}

                <form action="." method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea type="text" name="comment" class="form-control" placeholder="请填写评论"></textarea>
                    </div>
                    <input type="hidden" name="article_id" value="{{ article.id }}">
                    <div class="form-group" style="text-align: right">
                        <button class="btn btn-primary">立即评论</button>
                    </div>
                </form>

            </div>
            </div>

            <script src='{% static "js/jquery-1.11.1.min.js" %}'></script>
            <script src='{% static "editor/lib/marked.min.js" %}'></script>
            <script src='{% static "editor/lib/prettify.min.js" %}'></script>
            <script src='{% static "editor/lib/raphael.min.js" %}'></script>
            <script src='{% static "editor/lib/underscore.min.js" %}'></script>
            <script src='{% static "editor/lib/sequence-diagram.min.js" %}'></script>
            <script src='{% static "editor/lib/flowchart.min.js" %}'></script>
            <script src='{% static "editor/lib/jquery.flowchart.min.js" %}'></script>
            <script src='{% static "editor/editormd.js" %}'></script>
            <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
            <script type="text/javascript">
                $(function () {
                    editormd.markdownToHTML("editormd-view", {
                        htmlDecode: "style, script, iframe",
                        emoji: true,
                        taskList: true,
                        tex: true,
                        flowChart: true,
                        sequenceDiagram: true,
                    });
                });

                function like_article(id, action) {
                    $.ajax({
                        url: "{% url 'article:like_article' %}",
                        type: "POST",
                        data: {"id": id, "action": action},
                        success: function (e) {
                            if (e == "1") {
                                layer.msg("感谢点赞", {
                                    time: 700,
                                    end: function () {
                                        window.location.reload();
                                    }

                                });

                            } else {
                                layer.msg("我会继续努力", {
                                    time: 700,
                                    end: function () {
                                        window.location.reload();
                                    }

                                });
                            }
                        },
                    });
                }

            </script>


            {#        <div class="line-control">#}
            {##}
            {#            <div class="font-control">#}
            {#                <h4>评论: </h4>#}
            {#            </div>#}
            {##}
            {#            <form action="{{ url_for('content') }}" method="post">#}
            {#                <div class="form-group">#}
            {#                    <input type="text" name="content" class="form-control" placeholder="请填写评论">#}
            {#                </div>#}
            {#                <input type="hidden" name="question_id" value="{{ question.id }}">#}
            {#                <div class="form-group" style="text-align: right">#}
            {#                    <button class="btn btn-primary">立即评论</button>#}
            {#                </div>#}
            {#            </form>#}
            {#            <ul class="answer-list">#}
            {#                {% for answer in question.answers %}#}
            {#                    <div class="user-info">#}
            {#                    <img src="{{ url_for('static',filename='') }}"alt="" class="avatar">#}
            {#                        <span class="username">{{ answer.author.username }}</span>#}
            {#                        <span class="create-time">{{ answer.create_time }}</span>#}
            {#                    </div>#}
            {#                    <p class="answer-content">{{ answer.content }}</p>#}
            {#                    <hr>#}
            {#                {% endfor %}#}
            {#            </ul>#}
            {#        </div>#}
            <style>
                .main {
                    background: #fff;
                    width: 750px;
                    margin: 0 auto;
                    overflow: hidden;
                    padding: 10px;
                }

                .page-title {
                    text-align: center;
                    font-weight: 800;
                }

                .question-info {
                    text-align: center;
                    margin-top: 20px;

                }

                .question-content {
                    margin-left: 10px;
                }

                .span {
                    margin-right: 10px;
                }

                .form-control {
                    width: 650px;
                }

                .form-group {
                    margin-left: 10px;
                }

                .font-control {
                    margin-left: 10px;
                }

                .form-group {
                    margin-right: 48px;
                }

                .line-control {
                    line-height: 300%;
                }

                .answer-list li {
                    list-style: none;
                    border-bottom: 1px solid #eee;
                    padding-top: 10px;
                }

                .answer-list {
                    padding-left: 0;
                }

                .user-info {
                    font-size: 16px;
                    color: #9b9b9b;
                    line-height: 40px;
                }

                .user-info .username {
                    margin-left: 20px;
                }

                .user-info .create-time {
                    float: right;
                }

                .answer-content {
                    margin-left: 60px;
                    font-size: 20px;
                }
            </style>
        {% endwith %}
    {% endblock %}
</div>